import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  env: {
    GOOGLE_CHAT_APPLICATION_CREDENTIALS_JSON:
      process.env.GOOGLE_CHAT_APPLICATION_CREDENTIALS_JSON,
    GOOGLE_PRIVATE_TYPE: process.env.GOOGLE_PRIVATE_TYPE,
    GOOGLE_PRIVATE_PROJECT_ID: process.env.GOOGLE_PRIVATE_PROJECT_ID,
    GOOGLE_PRIVATE_KEY_ID: process.env.GOOGLE_PRIVATE_KEY_ID,
    GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY,
    GOOGLE_PRIVATE_CLIENT_EMAIL: process.env.GOOGLE_PRIVATE_CLIENT_EMAIL,
    GOOGLE_PRIVATE_CLIENT_ID: process.env.GOOGLE_PRIVATE_CLIENT_ID,
    GOOGLE_PRIVATE_AUTH_URI: process.env.GOOGLE_PRIVATE_AUTH_URI,
    GOOGLE_PRIVATE_TOKEN_URI: process.env.GOOGLE_PRIVATE_TOKEN_URI,
    GOOGLE_PRIVATE_AUTH_PROVIDER_X509_CERT_URL:
      process.env.GOOGLE_PRIVATE_AUTH_PROVIDER_X509_CERT_URL,
    GOOGLE_PRIVATE_CLIENT_X509_CERT_URL:
      process.env.GOOGLE_PRIVATE_CLIENT_X509_CERT_URL,
    GOOGLE_PRIVATE_UNIVERSE_DOMAIN: process.env.GOOGLE_PRIVATE_UNIVERSE_DOMAIN,
  },
};

export default nextConfig;
